baseURL = 'https://bolab.dev/'
title = "Bo's Lab"

defaultContentLanguage = 'zh-cn'
hasCJKLanguage = true

[pagination]
  pagerSize = 20

[permalinks]
  post = '/p/:slug/'
  page = '/:slug/'

[markup]
  [markup.highlight]
    lineNos = true
    noClasses = false
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
  home = ['HTML', 'RSS']
