[[main]]
  identifier = 'home'
  name = '首页'
  url = '/'
  weight = 1
  [main.params]
    icon = 'home'

[[main]]
  identifier = 'archives'
  name = '归档'
  url = '/archives'
  weight = 2
  [main.params]
    icon = 'archives'

[[main]]
  identifier = 'search'
  name = '搜索'
  url = '/search'
  weight = 3
  [main.params]
    icon = 'search'

[[social]]
  identifier = 'github'
  name = 'GitHub'
  url = 'https://github.com/wytoumao'
  [social.params]
    icon = 'brand-github'

[[social]]
  identifier = 'twitter'
  name = 'Twitter'
  url = 'https://twitter.com/'
  [social.params]
    icon = 'brand-twitter'
