mainSections = ['post']
rssFullContent = true
favicon = ''

[footer]
  since = 2025

[sidebar]
  emoji = 'ğŸ§ª'
  subtitle = "åŒºå—é“¾ Â· æµ‹è¯• Â· AI"

[article]
  math = false
  toc = true
  readingTime = true

[widgets]
  homepage = [
    { type = "search" },
    { type = "archives", params = { limit = 5 } },
    { type = "categories", params = { limit = 10 } },
    { type = "tag-cloud", params = { limit = 10 } },
  ]
  page = [{ type = "toc" }]

[comments]
  enabled = false
